// Compagnie aeree rilevanti per il Reg. UE 261/2004
// Include vettori UE/SEE/UK e compagnie extra-UE che operano voli in partenza da aeroporti europei

export const AIRLINES_MANUAL: string[] = [
  // ── UE / SEE / UK ──────────────────────────────────────────────────────────
  "Aegean Airlines",
  "Aer Lingus",
  "airBaltic",
  "Air Corsica",
  "Air Dolomiti",
  "Air Europa",
  "Air France",
  "Air Nostrum (Iberia Regional)",
  "Air Serbia",
  "Austrian Airlines",
  "Azores Airlines (SATA)",
  "Binter Canarias",
  "Blue Air",
  "British Airways",
  "Brussels Airlines",
  "Bulgaria Air",
  "Condor",
  "Corendon Airlines",
  "Croatia Airlines",
  "easyJet",
  "Enter Air",
  "Eurowings",
  "Finnair",
  "Helvetic Airways",
  "Iberia",
  "Iberia Express",
  "Icelandair",
  "ITA Airways",
  "Jet2.com",
  "KLM",
  "Lauda Europe",
  "Loganair",
  "LOT Polish Airlines",
  "Luxair",
  "Malta Air",
  "Neos",
  "Norwegian Air International",
  "Norwegian Air Shuttle",
  "Pegasus Airlines",
  "PLAY",
  "Pobeda Airlines",
  "Ryanair",
  "SAS Scandinavian Airlines",
  "Sky Express",
  "Smartwings",
  "SunExpress",
  "SWISS",
  "TAP Air Portugal",
  "Tarom",
  "Transavia",
  "TUI fly Belgium",
  "TUI fly Deutschland",
  "TUI fly Netherlands",
  "TUI Airways (UK)",
  "Volotea",
  "Vueling",
  "Widerøe",
  "Wizz Air",
  "Wizz Air Malta",
  "Wizz Air UK",

  // ── Medio Oriente ───────────────────────────────────────────────────────────
  "Air Arabia",
  "Air Arabia Abu Dhabi",
  "Emirates",
  "Etihad Airways",
  "flydubai",
  "Gulf Air",
  "Kuwait Airways",
  "Middle East Airlines",
  "Oman Air",
  "Qatar Airways",
  "Royal Jordanian",
  "Saudia (Saudi Arabian Airlines)",

  // ── Africa ──────────────────────────────────────────────────────────────────
  "Air Algérie",
  "Air Madagascar",
  "Air Mauritius",
  "Corsair International",
  "EgyptAir",
  "Ethiopian Airlines",
  "Kenya Airways",
  "Royal Air Maroc",
  "South African Airways",
  "TAAG Angola Airlines",
  "Tunisair",

  // ── Nord America ────────────────────────────────────────────────────────────
  "Air Canada",
  "Air Transat",
  "American Airlines",
  "Delta Air Lines",
  "United Airlines",
  "WestJet",

  // ── Asia / Pacifico ─────────────────────────────────────────────────────────
  "Air India",
  "ANA (All Nippon Airways)",
  "Asiana Airlines",
  "Cathay Pacific",
  "China Airlines",
  "China Eastern Airlines",
  "China Southern Airlines",
  "Hainan Airlines",
  "IndiGo",
  "Japan Airlines",
  "Korean Air",
  "Malaysia Airlines",
  "Philippine Airlines",
  "Singapore Airlines",
  "SriLankan Airlines",
  "Thai Airways",
  "Turkish Airlines",
  "Vietnam Airlines",

  // ── Centro / Sud America ────────────────────────────────────────────────────
  "Aerolíneas Argentinas",
  "Aeroméxico",
  "Avianca",
  "LATAM Airlines",

  // ── Altro ───────────────────────────────────────────────────────────────────
  "Aeroflot",
  "Air Astana",
  "Arkia Israeli Airlines",
  "El Al",
]
