export const AIRLINES_MANUAL: string[] = [
  "Aegean Airlines",
  "Aer Lingus",
  "airBaltic",
  "Air Corsica",
  "Air Dolomiti",
  "Air Europa",
  "Air France",
  "Air Nostrum (Iberia Regional)",
  "Air Serbia",
  "Austrian Airlines",
  "Azores Airlines (SATA)",
  "Binter Canarias",
  "British Airways",
  "Brussels Airlines",
  "Bulgaria Air",
  "Condor",
  "Corendon Airlines Group (TR/MT/NL)",
  "Croatia Airlines",
  "easyJet (Group)",
  "Enter Air",
  "Eurowings",
  "Finnair",
  "Helvetic Airways",
  "Iberia",
  "Iberia Express",
  "Icelandair",
  "ITA Airways",
  "Jet2.com",
  "KLM",
  "Loganair",
  "LOT Polish Airlines",
  "Luxair",
  "Neos",
  "Norwegian Air Shuttle",
  "Pegasus Airlines",
  "PLAY",
  "Ryanair (Group)",
  "SAS Scandinavian Airlines",
  "Sky Express (Greece)",
  "Smartwings",
  "SunExpress",
  "SWISS",
  "TAP Air Portugal",
  "Transavia (Group)",
  "TUI Group (UK/DE/BE/NL)",
  "Volotea",
  "Vueling",
  "Widerøe",
  "Wizz Air (Group)",
]
